# Use official Python image
FROM python:3.11-slim

# Set work directory
WORKDIR /app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m pip install Pillow
# Copy project files
COPY . .

# Expose port
EXPOSE 8000

# Run Django server (replace 'myproject' with your project name)
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
